package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// HookName is the Git hook managed by Cosca.
const HookName = "post-commit"

// hookMarker identifies hook scripts generated by `cosca hook install`.
const hookMarker = "COSCA_HOOK_GENERATED=1"

// InstallHooks installs the Cosca post-commit hook into the Git repository
// at repoDir. The hook is written as an executable shell script that invokes
// the cosca binary (`cosca hook post-commit`) when Git triggers it.
//
// It returns the number of hooks installed and the number already present
// (skipped). Re-running is idempotent: if the installed script already
// matches the current one it is skipped. If our own script is outdated (e.g.
// the binary moved) it is upgraded in place. Foreign hooks are backed up to
// post-commit.bak.<timestamp> before being replaced, mirroring the legacy
// install-hooks.sh behaviour.
func InstallHooks(repoDir string) (installed int, skipped int, err error) {
	gitDir, err := gitDirFor(repoDir)
	if err != nil {
		return 0, 0, err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return 0, 0, fmt.Errorf("create hooks dir %s: %w", hooksDir, err)
	}

	script, err := hookScript()
	if err != nil {
		return 0, 0, err
	}

	target := filepath.Join(hooksDir, HookName)

	// ── Existing hook handling ──────────────────────────────────────────────
	if data, rerr := os.ReadFile(target); rerr == nil {
		if string(data) == script {
			// Already installed with the exact current script — nothing to do.
			skipped++
			return installed, skipped, nil
		}
		if !strings.Contains(string(data), hookMarker) {
			// Foreign hook: back it up before replacing.
			backup := fmt.Sprintf("%s.bak.%d", target, time.Now().Unix())
			if err := os.Rename(target, backup); err != nil {
				return 0, 0, fmt.Errorf("backup existing hook to %s: %w", backup, err)
			}
		}
		// Ours but outdated (binary moved, script changed): upgrade in place.
	}

	if err := os.WriteFile(target, []byte(script), 0o755); err != nil {
		return 0, 0, fmt.Errorf("write hook %s: %w", target, err)
	}
	installed++

	return installed, skipped, nil
}

// hookScript renders the shell script installed into .git/hooks/post-commit.
// The script prefers the absolute path of the binary that ran
// `cosca hook install` (the known-good binary) and falls back to the cosca
// binary from PATH (in case the binary moved or was rebuilt elsewhere). If
// neither is available it exits 0 so the commit is never broken.
//
// COSCA_LOG_LEVEL defaults to "error" so routine commits stay quiet unless
// the user explicitly overrides it.
func hookScript() (string, error) {
	bin := "cosca"
	if exe, err := os.Executable(); err == nil && exe != "" {
		bin = exe
	}

	return fmt.Sprintf(`#!/bin/sh
# Cosca %s hook — generated by "cosca hook install".
# Marker: %s
# Regenerate with: cosca hook install
#
# Safety: this hook only reads git data and writes report files under
# .cosca/. It never creates commits, so it cannot recursively trigger
# itself.
if [ -x %s ]; then
    COSCA_LOG_LEVEL="${COSCA_LOG_LEVEL:-error}" exec %s hook post-commit
fi
if command -v cosca >/dev/null 2>&1; then
    COSCA_LOG_LEVEL="${COSCA_LOG_LEVEL:-error}" exec cosca hook post-commit
fi
exit 0
`, HookName, hookMarker, shellQuote(bin), shellQuote(bin)), nil
}

// shellQuote wraps s in single quotes, escaping embedded single quotes the
// way POSIX sh expects.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
