package cli

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/CoscaAI/cosca/internal/hooks"
)

// NewHookCommand creates the `cosca hook` command group for managing the
// Cosca Git hooks (post-commit impact report automation).
func NewHookCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "hook",
		Short: "Manage Cosca Git hooks",
		Long: `Manage the Cosca Git hooks.

Cosca installs a post-commit hook that automatically generates an Impact
Report for every commit under .cosca/memory/timeline/ and appends an entry
to .cosca/memory/timeline/ENGINEERING_TIMELINE.md.

This replaces the legacy bash hooks (install-hooks.sh + post-commit) with
native functionality baked into the cosca binary.`,
		Example: `  cosca hook install         # Install hooks into the current repository
  cosca hook post-commit    # Generate an Impact Report for HEAD`,
	}

	cmd.AddCommand(
		NewHookInstallCommand(),
		NewHookPostCommitCommand(),
	)

	return cmd
}

// NewHookInstallCommand creates the `cosca hook install` command.
func NewHookInstallCommand() *cobra.Command {
	var dir string

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install Cosca hooks into the current Git repository",
		Long: `Install the Cosca post-commit hook into .git/hooks/ of the current
repository (or the one given via --dir).

The installed hook invokes "cosca hook post-commit" whenever Git fires it.
Existing hooks that were not generated by Cosca are backed up before being
replaced. Re-running the command is a no-op.`,
		Example: `  cosca hook install
  cosca hook install --dir /path/to/repo`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			abs, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolve directory: %w", err)
			}

			installed, skipped, err := hooks.InstallHooks(abs)
			if err != nil {
				return err
			}

			formatter := GetFormatter(cmd)
			if installed > 0 {
				formatter.Success(fmt.Sprintf("Installed %d hook(s) in %s", installed, abs))
			}
			if skipped > 0 {
				formatter.Println(fmt.Sprintf("%d hook(s) already installed — nothing to do", skipped))
			}
			formatter.Println("")
			formatter.Bullet("Test it: make a commit and check .cosca/memory/timeline/impact-reports/")
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", ".", "repository directory (default: current directory)")
	return cmd
}

// NewHookPostCommitCommand creates the `cosca hook post-commit` command.
func NewHookPostCommitCommand() *cobra.Command {
	var dir string

	cmd := &cobra.Command{
		Use:   "post-commit",
		Short: "Generate an Impact Report for the latest commit",
		Long: `Generate an Impact Report for the most recent commit (HEAD).

This is the command the installed Git hook invokes after every commit. It
can also be run manually to (re)generate the report for HEAD. Re-running is
idempotent: if the report for the commit already exists, it is returned as-is
and the timeline is not duplicated.

Commits that only touch .cosca/ (the hook's own output) are skipped so the
hook can never cause recursive report generation.`,
		Example: `  cosca hook post-commit
  cosca hook post-commit --dir /path/to/repo`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			abs, err := filepath.Abs(dir)
			if err != nil {
				return fmt.Errorf("resolve directory: %w", err)
			}

			report, err := hooks.GenerateImpactReport(abs)
			if err != nil {
				return err
			}

			formatter := GetFormatter(cmd)
			if report == "" {
				formatter.Println("Skipped: commit only touches .cosca/ — no Impact Report generated")
				return nil
			}
			formatter.Success("Impact Report generated")
			formatter.KeyValue("Report", report)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", ".", "repository directory (default: current directory)")
	return cmd
}
