// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/cosca/v1/knowledge.proto

package cospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Types         []string               `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
	PathFilter    string                 `protobuf:"bytes,5,opt,name=path_filter,json=pathFilter,proto3" json:"path_filter,omitempty"`
	MinScore      float64                `protobuf:"fixed64,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SearchRequest) GetPathFilter() string {
	if x != nil {
		return x.PathFilter
	}
	return ""
}

func (x *SearchRequest) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Facets        []*Facet               `protobuf:"bytes,4,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SearchResponse) GetFacets() []*Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Facet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Counts        map[string]int32       `protobuf:"bytes,2,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *Facet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Facet) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *IndexRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type IndexResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentsIndexed int32                  `protobuf:"varint,1,opt,name=documents_indexed,json=documentsIndexed,proto3" json:"documents_indexed,omitempty"`
	ChunksIndexed    int32                  `protobuf:"varint,2,opt,name=chunks_indexed,json=chunksIndexed,proto3" json:"chunks_indexed,omitempty"`
	Errors           []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *IndexResponse) GetDocumentsIndexed() int32 {
	if x != nil {
		return x.DocumentsIndexed
	}
	return 0
}

func (x *IndexResponse) GetChunksIndexed() int32 {
	if x != nil {
		return x.ChunksIndexed
	}
	return 0
}

func (x *IndexResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentCount int32                  `protobuf:"varint,1,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	ChunkCount    int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	EntityCount   int32                  `protobuf:"varint,3,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	VectorCount   int32                  `protobuf:"varint,4,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	DbSizeBytes   int64                  `protobuf:"varint,5,opt,name=db_size_bytes,json=dbSizeBytes,proto3" json:"db_size_bytes,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *StatsResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *StatsResponse) GetEntityCount() int32 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *StatsResponse) GetVectorCount() int32 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *StatsResponse) GetDbSizeBytes() int64 {
	if x != nil {
		return x.DbSizeBytes
	}
	return 0
}

func (x *StatsResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed       int32                  `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *SyncResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *SyncResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *SyncResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

func (x *SyncResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_cosca_v1_knowledge_proto protoreflect.FileDescriptor

const file_proto_cosca_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/cosca/v1/knowledge.proto\x12\bcosca.v1\"\xa7\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05types\x18\x04 \x03(\tR\x05types\x12\x1f\n" +
	"\vpath_filter\x18\x05 \x01(\tR\n" +
	"pathFilter\x12\x1b\n" +
	"\tmin_score\x18\x06 \x01(\x01R\bminScore\"\xa2\x01\n" +
	"\x0eSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.cosca.v1.SearchResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\x12'\n" +
	"\x06facets\x18\x04 \x03(\v2\x0f.cosca.v1.FacetR\x06facets\"\x8c\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\"\x8b\x01\n" +
	"\x05Facet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x06counts\x18\x02 \x03(\v2\x1b.cosca.v1.Facet.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"@\n" +
	"\fIndexRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"{\n" +
	"\rIndexResponse\x12+\n" +
	"\x11documents_indexed\x18\x01 \x01(\x05R\x10documentsIndexed\x12%\n" +
	"\x0echunks_indexed\x18\x02 \x01(\x05R\rchunksIndexed\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x0e\n" +
	"\fStatsRequest\"\xe8\x01\n" +
	"\rStatsResponse\x12%\n" +
	"\x0edocument_count\x18\x01 \x01(\x05R\rdocumentCount\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount\x12!\n" +
	"\fentity_count\x18\x03 \x01(\x05R\ventityCount\x12!\n" +
	"\fvector_count\x18\x04 \x01(\x05R\vvectorCount\x12\"\n" +
	"\rdb_size_bytes\x18\x05 \x01(\x03R\vdbSizeBytes\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x01R\ruptimeSeconds\"\r\n" +
	"\vSyncRequest\"p\n" +
	"\fSyncResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\x05R\aremoved\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors2\xfa\x01\n" +
	"\x10KnowledgeService\x12;\n" +
	"\x06Search\x12\x17.cosca.v1.SearchRequest\x1a\x18.cosca.v1.SearchResponse\x128\n" +
	"\x05Index\x12\x16.cosca.v1.IndexRequest\x1a\x17.cosca.v1.IndexResponse\x128\n" +
	"\x05Stats\x12\x16.cosca.v1.StatsRequest\x1a\x17.cosca.v1.StatsResponse\x125\n" +
	"\x04Sync\x12\x15.cosca.v1.SyncRequest\x1a\x16.cosca.v1.SyncResponseB,Z*github.com/CoscaAI/cosca/api/grpc/pb;cospbb\x06proto3"

var (
	file_proto_cosca_v1_knowledge_proto_rawDescOnce sync.Once
	file_proto_cosca_v1_knowledge_proto_rawDescData []byte
)

func file_proto_cosca_v1_knowledge_proto_rawDescGZIP() []byte {
	file_proto_cosca_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_proto_cosca_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_knowledge_proto_rawDesc), len(file_proto_cosca_v1_knowledge_proto_rawDesc)))
	})
	return file_proto_cosca_v1_knowledge_proto_rawDescData
}

var file_proto_cosca_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_cosca_v1_knowledge_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: cosca.v1.SearchRequest
	(*SearchResponse)(nil), // 1: cosca.v1.SearchResponse
	(*SearchResult)(nil),   // 2: cosca.v1.SearchResult
	(*Facet)(nil),          // 3: cosca.v1.Facet
	(*IndexRequest)(nil),   // 4: cosca.v1.IndexRequest
	(*IndexResponse)(nil),  // 5: cosca.v1.IndexResponse
	(*StatsRequest)(nil),   // 6: cosca.v1.StatsRequest
	(*StatsResponse)(nil),  // 7: cosca.v1.StatsResponse
	(*SyncRequest)(nil),    // 8: cosca.v1.SyncRequest
	(*SyncResponse)(nil),   // 9: cosca.v1.SyncResponse
	nil,                    // 10: cosca.v1.Facet.CountsEntry
}
var file_proto_cosca_v1_knowledge_proto_depIdxs = []int32{
	2,  // 0: cosca.v1.SearchResponse.results:type_name -> cosca.v1.SearchResult
	3,  // 1: cosca.v1.SearchResponse.facets:type_name -> cosca.v1.Facet
	10, // 2: cosca.v1.Facet.counts:type_name -> cosca.v1.Facet.CountsEntry
	0,  // 3: cosca.v1.KnowledgeService.Search:input_type -> cosca.v1.SearchRequest
	4,  // 4: cosca.v1.KnowledgeService.Index:input_type -> cosca.v1.IndexRequest
	6,  // 5: cosca.v1.KnowledgeService.Stats:input_type -> cosca.v1.StatsRequest
	8,  // 6: cosca.v1.KnowledgeService.Sync:input_type -> cosca.v1.SyncRequest
	1,  // 7: cosca.v1.KnowledgeService.Search:output_type -> cosca.v1.SearchResponse
	5,  // 8: cosca.v1.KnowledgeService.Index:output_type -> cosca.v1.IndexResponse
	7,  // 9: cosca.v1.KnowledgeService.Stats:output_type -> cosca.v1.StatsResponse
	9,  // 10: cosca.v1.KnowledgeService.Sync:output_type -> cosca.v1.SyncResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_cosca_v1_knowledge_proto_init() }
func file_proto_cosca_v1_knowledge_proto_init() {
	if File_proto_cosca_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_knowledge_proto_rawDesc), len(file_proto_cosca_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cosca_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_proto_cosca_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_proto_cosca_v1_knowledge_proto_msgTypes,
	}.Build()
	File_proto_cosca_v1_knowledge_proto = out.File
	file_proto_cosca_v1_knowledge_proto_goTypes = nil
	file_proto_cosca_v1_knowledge_proto_depIdxs = nil
}
