// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/cosca/v1/memory.proto

package cospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Ttl           string                 `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StoreRequest) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *StoreRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StoreRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *StoreRequest) GetTtl() string {
	if x != nil {
		return x.Ttl
	}
	return ""
}

func (x *StoreRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoreResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MemorySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Layers        []string               `protobuf:"bytes,3,rep,name=layers,proto3" json:"layers,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchRequest) Reset() {
	*x = MemorySearchRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchRequest) ProtoMessage() {}

func (x *MemorySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchRequest.ProtoReflect.Descriptor instead.
func (*MemorySearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *MemorySearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MemorySearchRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *MemorySearchRequest) GetLayers() []string {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *MemorySearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MemorySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*MemoryRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchResponse) Reset() {
	*x = MemorySearchResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchResponse) ProtoMessage() {}

func (x *MemorySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchResponse.ProtoReflect.Descriptor instead.
func (*MemorySearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *MemorySearchResponse) GetRecords() []*MemoryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *MemorySearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MemoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Layer         string                 `protobuf:"bytes,3,opt,name=layer,proto3" json:"layer,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryRecord) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *MemoryRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryRecord) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MemoryRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MemoryRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRequest) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *MemoryRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetRecord() *MemoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Layer         string                 `protobuf:"bytes,2,opt,name=layer,proto3" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PromoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromLayer     string                 `protobuf:"bytes,2,opt,name=from_layer,json=fromLayer,proto3" json:"from_layer,omitempty"`
	ToLayer       string                 `protobuf:"bytes,3,opt,name=to_layer,json=toLayer,proto3" json:"to_layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteRequest) Reset() {
	*x = PromoteRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteRequest) ProtoMessage() {}

func (x *PromoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteRequest.ProtoReflect.Descriptor instead.
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *PromoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PromoteRequest) GetFromLayer() string {
	if x != nil {
		return x.FromLayer
	}
	return ""
}

func (x *PromoteRequest) GetToLayer() string {
	if x != nil {
		return x.ToLayer
	}
	return ""
}

type PromoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *MemoryRecord          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteResponse) Reset() {
	*x = PromoteResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteResponse) ProtoMessage() {}

func (x *PromoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteResponse.ProtoReflect.Descriptor instead.
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *PromoteResponse) GetRecord() *MemoryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type MemoryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStatsRequest) Reset() {
	*x = MemoryStatsRequest{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatsRequest) ProtoMessage() {}

func (x *MemoryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatsRequest.ProtoReflect.Descriptor instead.
func (*MemoryStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{11}
}

type MemoryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layers        map[string]*LayerStats `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryStatsResponse) Reset() {
	*x = MemoryStatsResponse{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatsResponse) ProtoMessage() {}

func (x *MemoryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatsResponse.ProtoReflect.Descriptor instead.
func (*MemoryStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *MemoryStatsResponse) GetLayers() map[string]*LayerStats {
	if x != nil {
		return x.Layers
	}
	return nil
}

type LayerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordCount   int32                  `protobuf:"varint,1,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LayerStats) Reset() {
	*x = LayerStats{}
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerStats) ProtoMessage() {}

func (x *LayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerStats.ProtoReflect.Descriptor instead.
func (*LayerStats) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *LayerStats) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *LayerStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_proto_cosca_v1_memory_proto protoreflect.FileDescriptor

const file_proto_cosca_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/cosca/v1/memory.proto\x12\bcosca.v1\"\x95\x02\n" +
	"\fStoreRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\tR\x03ttl\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.cosca.v1.StoreRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\"o\n" +
	"\x13MemorySearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types\x12\x16\n" +
	"\x06layers\x18\x03 \x03(\tR\x06layers\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"^\n" +
	"\x14MemorySearchResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.cosca.v1.MemoryRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9c\x02\n" +
	"\fMemoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\tR\x05layer\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.cosca.v1.MemoryRecord.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\"=\n" +
	"\vGetResponse\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.cosca.v1.MemoryRecordR\x06record\"5\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\tR\x05layer\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x0ePromoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"from_layer\x18\x02 \x01(\tR\tfromLayer\x12\x19\n" +
	"\bto_layer\x18\x03 \x01(\tR\atoLayer\"A\n" +
	"\x0fPromoteResponse\x12.\n" +
	"\x06record\x18\x01 \x01(\v2\x16.cosca.v1.MemoryRecordR\x06record\"\x14\n" +
	"\x12MemoryStatsRequest\"\xa9\x01\n" +
	"\x13MemoryStatsResponse\x12A\n" +
	"\x06layers\x18\x01 \x03(\v2).cosca.v1.MemoryStatsResponse.LayersEntryR\x06layers\x1aO\n" +
	"\vLayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.cosca.v1.LayerStatsR\x05value:\x028\x01\"N\n" +
	"\n" +
	"LayerStats\x12!\n" +
	"\frecord_count\x18\x01 \x01(\x05R\vrecordCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes2\x89\x03\n" +
	"\rMemoryService\x128\n" +
	"\x05Store\x12\x16.cosca.v1.StoreRequest\x1a\x17.cosca.v1.StoreResponse\x12G\n" +
	"\x06Search\x12\x1d.cosca.v1.MemorySearchRequest\x1a\x1e.cosca.v1.MemorySearchResponse\x122\n" +
	"\x03Get\x12\x14.cosca.v1.GetRequest\x1a\x15.cosca.v1.GetResponse\x12;\n" +
	"\x06Delete\x12\x17.cosca.v1.DeleteRequest\x1a\x18.cosca.v1.DeleteResponse\x12>\n" +
	"\aPromote\x12\x18.cosca.v1.PromoteRequest\x1a\x19.cosca.v1.PromoteResponse\x12D\n" +
	"\x05Stats\x12\x1c.cosca.v1.MemoryStatsRequest\x1a\x1d.cosca.v1.MemoryStatsResponseB,Z*github.com/CoscaAI/cosca/api/grpc/pb;cospbb\x06proto3"

var (
	file_proto_cosca_v1_memory_proto_rawDescOnce sync.Once
	file_proto_cosca_v1_memory_proto_rawDescData []byte
)

func file_proto_cosca_v1_memory_proto_rawDescGZIP() []byte {
	file_proto_cosca_v1_memory_proto_rawDescOnce.Do(func() {
		file_proto_cosca_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_memory_proto_rawDesc), len(file_proto_cosca_v1_memory_proto_rawDesc)))
	})
	return file_proto_cosca_v1_memory_proto_rawDescData
}

var file_proto_cosca_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_cosca_v1_memory_proto_goTypes = []any{
	(*StoreRequest)(nil),         // 0: cosca.v1.StoreRequest
	(*StoreResponse)(nil),        // 1: cosca.v1.StoreResponse
	(*MemorySearchRequest)(nil),  // 2: cosca.v1.MemorySearchRequest
	(*MemorySearchResponse)(nil), // 3: cosca.v1.MemorySearchResponse
	(*MemoryRecord)(nil),         // 4: cosca.v1.MemoryRecord
	(*GetRequest)(nil),           // 5: cosca.v1.GetRequest
	(*GetResponse)(nil),          // 6: cosca.v1.GetResponse
	(*DeleteRequest)(nil),        // 7: cosca.v1.DeleteRequest
	(*DeleteResponse)(nil),       // 8: cosca.v1.DeleteResponse
	(*PromoteRequest)(nil),       // 9: cosca.v1.PromoteRequest
	(*PromoteResponse)(nil),      // 10: cosca.v1.PromoteResponse
	(*MemoryStatsRequest)(nil),   // 11: cosca.v1.MemoryStatsRequest
	(*MemoryStatsResponse)(nil),  // 12: cosca.v1.MemoryStatsResponse
	(*LayerStats)(nil),           // 13: cosca.v1.LayerStats
	nil,                          // 14: cosca.v1.StoreRequest.MetadataEntry
	nil,                          // 15: cosca.v1.MemoryRecord.MetadataEntry
	nil,                          // 16: cosca.v1.MemoryStatsResponse.LayersEntry
}
var file_proto_cosca_v1_memory_proto_depIdxs = []int32{
	14, // 0: cosca.v1.StoreRequest.metadata:type_name -> cosca.v1.StoreRequest.MetadataEntry
	4,  // 1: cosca.v1.MemorySearchResponse.records:type_name -> cosca.v1.MemoryRecord
	15, // 2: cosca.v1.MemoryRecord.metadata:type_name -> cosca.v1.MemoryRecord.MetadataEntry
	4,  // 3: cosca.v1.GetResponse.record:type_name -> cosca.v1.MemoryRecord
	4,  // 4: cosca.v1.PromoteResponse.record:type_name -> cosca.v1.MemoryRecord
	16, // 5: cosca.v1.MemoryStatsResponse.layers:type_name -> cosca.v1.MemoryStatsResponse.LayersEntry
	13, // 6: cosca.v1.MemoryStatsResponse.LayersEntry.value:type_name -> cosca.v1.LayerStats
	0,  // 7: cosca.v1.MemoryService.Store:input_type -> cosca.v1.StoreRequest
	2,  // 8: cosca.v1.MemoryService.Search:input_type -> cosca.v1.MemorySearchRequest
	5,  // 9: cosca.v1.MemoryService.Get:input_type -> cosca.v1.GetRequest
	7,  // 10: cosca.v1.MemoryService.Delete:input_type -> cosca.v1.DeleteRequest
	9,  // 11: cosca.v1.MemoryService.Promote:input_type -> cosca.v1.PromoteRequest
	11, // 12: cosca.v1.MemoryService.Stats:input_type -> cosca.v1.MemoryStatsRequest
	1,  // 13: cosca.v1.MemoryService.Store:output_type -> cosca.v1.StoreResponse
	3,  // 14: cosca.v1.MemoryService.Search:output_type -> cosca.v1.MemorySearchResponse
	6,  // 15: cosca.v1.MemoryService.Get:output_type -> cosca.v1.GetResponse
	8,  // 16: cosca.v1.MemoryService.Delete:output_type -> cosca.v1.DeleteResponse
	10, // 17: cosca.v1.MemoryService.Promote:output_type -> cosca.v1.PromoteResponse
	12, // 18: cosca.v1.MemoryService.Stats:output_type -> cosca.v1.MemoryStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_cosca_v1_memory_proto_init() }
func file_proto_cosca_v1_memory_proto_init() {
	if File_proto_cosca_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_memory_proto_rawDesc), len(file_proto_cosca_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cosca_v1_memory_proto_goTypes,
		DependencyIndexes: file_proto_cosca_v1_memory_proto_depIdxs,
		MessageInfos:      file_proto_cosca_v1_memory_proto_msgTypes,
	}.Build()
	File_proto_cosca_v1_memory_proto = out.File
	file_proto_cosca_v1_memory_proto_goTypes = nil
	file_proto_cosca_v1_memory_proto_depIdxs = nil
}
