// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/cosca/v1/runtime.proto

package cospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	State         string                    `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Health        string                    `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	UptimeSeconds float64                   `protobuf:"fixed64,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version       string                    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Components    map[string]*ComponentInfo `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetComponents() map[string]*ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

type ComponentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds float64                `protobuf:"fixed64,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentInfo) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_runtime_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosca_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosca_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_proto_cosca_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_cosca_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/cosca/v1/runtime.proto\x12\bcosca.v1\"\x0f\n" +
	"\rStatusRequest\"\xa1\x02\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x16\n" +
	"\x06health\x18\x02 \x01(\tR\x06health\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x01R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12H\n" +
	"\n" +
	"components\x18\x05 \x03(\v2(.cosca.v1.StatusResponse.ComponentsEntryR\n" +
	"components\x1aV\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cosca.v1.ComponentInfoR\x05value:\x028\x01\"b\n" +
	"\rComponentInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x01R\ruptimeSeconds\"\x0f\n" +
	"\rHealthRequest\"F\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings2\x8a\x01\n" +
	"\x0eRuntimeService\x12;\n" +
	"\x06Status\x12\x17.cosca.v1.StatusRequest\x1a\x18.cosca.v1.StatusResponse\x12;\n" +
	"\x06Health\x12\x17.cosca.v1.HealthRequest\x1a\x18.cosca.v1.HealthResponseB,Z*github.com/CoscaAI/cosca/api/grpc/pb;cospbb\x06proto3"

var (
	file_proto_cosca_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_cosca_v1_runtime_proto_rawDescData []byte
)

func file_proto_cosca_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_cosca_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_cosca_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_runtime_proto_rawDesc), len(file_proto_cosca_v1_runtime_proto_rawDesc)))
	})
	return file_proto_cosca_v1_runtime_proto_rawDescData
}

var file_proto_cosca_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cosca_v1_runtime_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: cosca.v1.StatusRequest
	(*StatusResponse)(nil), // 1: cosca.v1.StatusResponse
	(*ComponentInfo)(nil),  // 2: cosca.v1.ComponentInfo
	(*HealthRequest)(nil),  // 3: cosca.v1.HealthRequest
	(*HealthResponse)(nil), // 4: cosca.v1.HealthResponse
	nil,                    // 5: cosca.v1.StatusResponse.ComponentsEntry
}
var file_proto_cosca_v1_runtime_proto_depIdxs = []int32{
	5, // 0: cosca.v1.StatusResponse.components:type_name -> cosca.v1.StatusResponse.ComponentsEntry
	2, // 1: cosca.v1.StatusResponse.ComponentsEntry.value:type_name -> cosca.v1.ComponentInfo
	0, // 2: cosca.v1.RuntimeService.Status:input_type -> cosca.v1.StatusRequest
	3, // 3: cosca.v1.RuntimeService.Health:input_type -> cosca.v1.HealthRequest
	1, // 4: cosca.v1.RuntimeService.Status:output_type -> cosca.v1.StatusResponse
	4, // 5: cosca.v1.RuntimeService.Health:output_type -> cosca.v1.HealthResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_cosca_v1_runtime_proto_init() }
func file_proto_cosca_v1_runtime_proto_init() {
	if File_proto_cosca_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cosca_v1_runtime_proto_rawDesc), len(file_proto_cosca_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cosca_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_cosca_v1_runtime_proto_depIdxs,
		MessageInfos:      file_proto_cosca_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_cosca_v1_runtime_proto = out.File
	file_proto_cosca_v1_runtime_proto_goTypes = nil
	file_proto_cosca_v1_runtime_proto_depIdxs = nil
}
